# Generated by Django 2.1.5 on 2020-05-05 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_basic', '0002_auto_20200505_0740'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articletype',
            name='name',
            field=models.CharField(max_length=256, unique=True, verbose_name='Article Type Name'),
        ),
    ]
